### ISSUE TITLE
Binary name should be xf not xenforo

### ISSUE THREAD

**Issue by chrisdeeming** [JakeBooher/xf-cli#1]
Small thing: This can be changed ourselves easily and `xf` is a little more ambiguous but it might be worth considering changing the binary name to that (preferably because it's shorter) or go with the same name as the repo, e.g. `xf-cli`.

Simple reason being is that's basically what we would expect to become more familiar over time. Different from XF1, we very rarely refer to XF2 as "XenForo" in the code. By contrast, it was pretty much the opposite in XF1.

So, little thing, but a name change (even though we can do it ourselves!) is probably something to think about.

**Comment by JakeBooher** [comment]
Makes sense to me, will probably do this when I get a chance to look at #2
